Error Messages for Incorrect Login Attempts #38
gcivil-nyu-org/wed-fall24-team1 pull request #68
Opened 2024-10-23 05:44 UTC by KartikeySharma

2024-10-28 19:39 UTC, aakashshankar requested changes
few comments. also please add some UTs to cover these changes 😉

2024-10-28 19:39 UTC, aakashshankar commented on src/accounts/backends.py
> +        except UserModel.DoesNotExist:
this looks good but I think we can just have username based auth for now. we can add a unique constraint on the email on the CustomUser model, and just fetch the username based on the email. i think that would be easier right?

2024-10-28 19:39 UTC, aakashshankar commented on src/accounts/forms.py
> +            if self.user_cache is None:
we could just fetch the username based on the email and perform a normal username based auth here. that's what i did for #87. you can look at the changes there (to add a unique constraint for the email field)

2024-10-28 19:41 UTC, aakashshankar commented
also merge conflicts. I'll work on moving the current dev environemnt's sqlite3 to a managed solution for #61

2024-10-29 00:01 UTC, omerfarukbasar approved these changes
Looks good to me!

2024-10-29 00:02 UTC, aakashshankar approved these changes
lgtm

2024-10-29 00:04 UTC, merged